# ----------- CONFIGURABLE START -----------
title:            "Blog ของแม็กเองคร๊าบ"
description:      "เป็นเพจ สำหรับไว้เก็บ เนื้อหา โน็ตการทำงานต่างๆ สรรพเพเหระ แบ่งเป็นหมวดๆ"
url:              https://lionants02.github.io # 域名
signoff:          "Thanachai Thongkum" # Your name
facebook_appid:   LoveThanachai #liberxue
google_analytics: UA-112596793-1
share:            true
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         หน้าแรก
    url:          /
    external:     false
  - name:         คลังเนื้อหา
    url:          /book
    external:     false
  - name:         แท๊กเนื้อหา
    url:          /tags
    external:     false
  - name:         เกี่ยวกับฉัน
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
